name: Main
on:
  pull_request:
    branches:
    - main
jobs:
  build-and-test:
    name: build and test
    runs-on: macos-13
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Select Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_14.3.1.app
      - name: Check Xcode Version
        run: xcodebuild -version
      - name: Build
        run: xcodebuild build-for-testing CODE_SIGNING_ALLOWED=NO -scheme "GithubActions" -destination "platform=iOS Simulator,name=iPhone 14"
